source 'http://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'ffi'
gem 'faker'
gem 'cpf_faker'
gem 'site_prism'
gem 'rspec'
gem 'allure-rspec'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'report_builder'
gem 'appium_lib'
